### ISSUE TITLE
Add Power Within Plebs

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#148]
They aren't really a popular team, just thought their logo was cool and should be added.
![plebs logo](https://cloud.githubusercontent.com/assets/18340066/14372085/39e23276-fcf2-11e5-8ab4-66398f14efe7.jpg)

**Comment by wyizzle** [comment]
![plebswhiteandblack](https://cloud.githubusercontent.com/assets/18340066/14396445/754a132a-fd8c-11e5-8bf6-ee5201c98547.jpg)

**Comment by kokarn** [comment]
Hey! Sorry i've been away so long. Do you have this with a transparent background?

**Comment by wyizzle** [comment]
Yes, I do!

**Comment by kokarn** [comment]
Nice! Could you link it somewhere?

**Comment by wyizzle** [comment]
Is just adding as an attachment fine?

**Comment by wyizzle** [comment]
I am away from PC rn, but I will be back on the 13th of august and send it
to you from there.

**Comment by kokarn** [comment]
Any way's fine. Just as long as where you post it doesn't compress. imgur
should work if for some reason the GitHub attachment doesn't :)

**Comment by wyizzle** [comment]
Okay, I will send it as soon as I am back on my PC!

**Comment by wyizzle** [comment]
Actually, I will try and use one of the PCs here, I might get it out
tommorow. But if there is no response it will probably be sent around
august 13th.

**Comment by kokarn** [comment]
No worries dude, I'll add it whenever :)

**Comment by wyizzle** [comment]
Alright!

**Comment by wyizzle** [comment]
Alright, I got it

**Comment by kokarn** [comment]
Did you come around to this?

**Comment by wyizzle** [comment]
Oh I thought it was sent in my last email, I will make a new issues for it
cause it doesn't seems to be sending the way I am attaching it.

**Comment by kokarn** [comment]
Yeah, I don't think it works to attach things via e-mail

**Comment by wyizzle** [comment]
K here it is. Hopefully.
![kokarnplebs](https://cloud.githubusercontent.com/assets/18340066/17744303/f4c50aca-645b-11e6-9659-b12f0dde4d3a.png)

**Comment by kokarn** [comment]
Looks great! Will add ASAP
