### ISSUE TITLE
Add KKona

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#149]
An upcoming NA team. They are in the ESL pro league and fighting it out to qualify for ECS.
![kkona](https://cloud.githubusercontent.com/assets/18340066/14372113/59650ce0-fcf2-11e5-8026-d253c6b82d88.png)

**Comment by kokarn** [comment]
Hey! Thanks for helping out. Do you happen to have this logo in a higher resolution anywhere?

**Comment by wyizzle** [comment]
Just saw the email, no I don't, the one I have comes directly from ESL, it
was the highest quality I could get. Sorry :(

**Comment by wyizzle** [comment]
Sorry for not responding, haven't checked email in a few days, but I
responded to both of your emails, so hope that helps.

**Comment by kokarn** [comment]
This works, just looking for stuff larger than 500x500. Thanks for helping out!
