### ISSUE TITLE
Add Tectonic

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#156]
They are a ESEA and CEVO team, they are also qualifying for Starladder Season 2, so they might become well known soon. This is the biggest image I could find.
![w0dcad1s_400x400](https://cloud.githubusercontent.com/assets/18340066/17603288/3379ccec-5fc5-11e6-834b-cab5db7064ca.png)

**Comment by kokarn** [comment]
Thanks! For some reason the GitHub upload doesn't seem to work very well as the logo is pretty small. I did however find another larger one. Cheers!

**Comment by wyizzle** [comment]
Alright, thanks.
