### ISSUE TITLE
Add Kingdom eSports

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#157]
They are a CEVO and ESEA premier level team. This is the biggest image I could find for now but I'm open to other people changing it if they find something better (or I can also).
![kingdom-logo](https://cloud.githubusercontent.com/assets/18340066/17603398/c2ec249c-5fc5-11e6-8cda-2c2c05d127b5.png)

**Comment by kokarn** [comment]
Thank you so much!

**Comment by wyizzle** [comment]
No problem. :)
