### ISSUE TITLE
Add Vault.gg

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#159]
They are another NA CEVO/ESEA team. Also, this is my last add for today ;)
![4ea8f4f2-265f-4731-85db-a1afb4af1b4f](https://cloud.githubusercontent.com/assets/18340066/17603904/12eb90fc-5fc8-11e6-9de3-ff23b1e7bc40.png)

**Comment by kokarn** [comment]
You can add as much as you like. I'll try to keep updating as much as possible :)

**Comment by wyizzle** [comment]
Okay. Just didn't want to spam you. Did the size work okay or is it too
small?

**Comment by kokarn** [comment]
It's a bit small. Not sure if it's github shrinking or what's happening. Just link the original from now on and i'll do what i can :)

**Comment by wyizzle** [comment]
Alright, do you want me to relink this one?

**Comment by kokarn** [comment]
If you find something with a great resolution, please do. The current one is 469x469 https://github.com/kokarn/csgo-data/blob/master/teams/Vault/logo-469x469.png
