### ISSUE TITLE
Add Heroic.gg

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#161]
Heroic is the new team formed by Team X. They are a danish team who just won Power Lan today as well. 
![heroic](https://cloud.githubusercontent.com/assets/18340066/18031655/6a672e4c-6ca0-11e6-9a6e-266479acdbc3.jpg) This is the best quality I could find.

**Comment by kokarn** [comment]
Thanks! Sorry I was so slow to add, was away this weekend.

**Comment by wyizzle** [comment]
Np, thanks for adding and replying.
