### ISSUE TITLE
Add 24/7 eSports

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#169]
Not much known, but they have 6 players and are listed in ESEA im pretty sure.
![24 7 esports](https://cloud.githubusercontent.com/assets/18340066/19099618/f90c0d4a-8a6c-11e6-8d6a-9ed0cf90f714.png)
![24 7 esports for kokarn](https://cloud.githubusercontent.com/assets/18340066/19099625/fe03eb42-8a6c-11e6-9bd3-39642f17f585.png)

**Comment by kokarn** [comment]
Seems like they don't have a CSGO team at the moment tho, and only creates content
http://www.247esports.com/announcements/247-esports-parts-way-with-counter-strike-global-offensive-team/

> 24/7 Esports is a growing content creation organisation providing a platform for content creators to promote their content through a central hub.

Also, no news or updates since March 1 :/

**Comment by wyizzle** [comment]
Oh okay, I forgot to check that lol.

I mainly used it because theScore recognizes it as an official team so
