### ISSUE TITLE
Add 3sUP Enterprises

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#170]
They are not currently fielding a team, but used to own the Splyce roster. They are still active so I thought it was important to add them.
![3sup enterprises](https://cloud.githubusercontent.com/assets/18340066/19100237/c0fe7ab4-8a71-11e6-8a66-b1a508a0be48.png)

**Comment by kokarn** [comment]
Thanks so much <3

**Comment by wyizzle** [comment]
np <3
