### ISSUE TITLE
Add Anox

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#171]
Anox are an upcoming team looking to make their mark during Epicenter, if they qualify.
![anox](https://cloud.githubusercontent.com/assets/18340066/19100882/b61ff9d2-8a77-11e6-9ac3-9ac9e4f1900f.png)

**Comment by kokarn** [comment]
Thanks! Great to see you still looking out for new teams <3

**Comment by wyizzle** [comment]
np! And dont worry, I will always look for new teams.
