### ISSUE TITLE
Add Mythic Reborn/Replace Mythic

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#172]
After Winterfox got a new roster, one of their players decided to remake Mythic, they have a new really cool logo. The only problem is the quality. Hopefully there will be a higher quality version sometime soon, but I thought it was important to update everything :). Here's their twitter:  https://twitter.com/MythicRebornGG
![mythic reborn](https://cloud.githubusercontent.com/assets/18340066/19216557/f3265a1e-8d75-11e6-82f6-e4b36e0a9194.png)

**Comment by kokarn** [comment]
Looks good. Think i'll wait until something that doesn't look horrible shows up but I'll keep it open :)

**Comment by wyizzle** [comment]
Alright!

**Comment by wyizzle** [comment]
I have found a much better quality image, hopefully it is good enough to be used here.
![mythic red](https://cloud.githubusercontent.com/assets/18340066/21993840/b8900558-dbd1-11e6-818c-51422beb80ed.png)

**Comment by kokarn** [comment]
Yeah that works. If you do stumble upon anything that looks better, please don't hesitate to send it to me. I'd greatly appreciate it.
