### ISSUE TITLE
Add Blight Gaming

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#174]
They are another NA ESEA/CEVO Main team. 

https://play.esea.net/teams/68773
http://blightgaming.com/team/
http://www.gosugamers.net/counterstrike/teams/17784-blight
(I just like linking every source I have on them)
![blight gaming](https://cloud.githubusercontent.com/assets/18340066/19545688/14d67af2-963d-11e6-8d08-687130859eb8.png)

**Comment by kokarn** [comment]
The more sources the better, so thanks for that <3
