### ISSUE TITLE
Add Outlaws

### ISSUE THREAD

**Issue by wyizzle** [kokarn/csgo-data#184]
http://www.hltv.org/?pageid=179&teamid=7397
![outlaws](https://cloud.githubusercontent.com/assets/18340066/20610363/622e9c18-b24d-11e6-9888-c4ea2efc79d7.JPG)

**Comment by kokarn** [comment]
I can't seem to find anything except for that HLTV listing.

Thinking it's just something temporary until they get picked up. Thoughts?

**Comment by wyizzle** [comment]
Yeah, if you couldnt find anything, probably just a temp. name.
